
spring:
  application:
    name: config
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: jinxd
    password: 781010
    url: jdbc:mysql://127.0.0.1:8081/dbgirl?characterEncoding=utf-8&useSSL=false
